language: node_js
node_js:
- 8.11.4

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/UAMIShop
  on:
    branch: master
    deploy:
  provider: releases
  api_key:  $GITHUB_TOKEN
  file: "test"
  skip_cleanup: true
  on:
    tags: true